In [1]:
import os
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/processed/telco_customer_churn_cleaned.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [5]:
print("Dataset Shape:", df.shape)

Dataset Shape: (7032, 21)

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
df["Churn"].value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [8]:
X = df.drop(columns=["customerID", "Churn"])

y = df["Churn"]

In [9]:
print("Feature Matrix Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Matrix Shape: (7032, 19)
Target Shape: (7032,)

In [10]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [11]:
target_encoder = LabelEncoder()

In [12]:
y = target_encoder.fit_transform(y)

In [13]:
print("Unique values:", np.unique(y))

print("\nFirst 10 values:")

print(y[:10])

Unique values: [0 1]

First 10 values:
[0 0 1 0 1 1 0 0 1 0]

In [14]:
categorical_columns = X.select_dtypes(include=["object", "string"]).columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')

In [15]:
print("Number of categorical columns:", len(categorical_columns))

Number of categorical columns: 15

In [16]:
X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True,
    dtype=int
)

In [17]:
print("Encoded Dataset Shape:", X.shape)

Encoded Dataset Shape: (7032, 30)

In [18]:
X.columns.tolist()

['SeniorCitizen',
 'tenure',
 'MonthlyCharges',
 'TotalCharges',
 'gender_Male',
 'Partner_Yes',
 'Dependents_Yes',
 'PhoneService_Yes',
 'MultipleLines_No phone service',
 'MultipleLines_Yes',
 'InternetService_Fiber optic',
 'InternetService_No',
 'OnlineSecurity_No internet service',
 'OnlineSecurity_Yes',
 'OnlineBackup_No internet service',
 'OnlineBackup_Yes',
 'DeviceProtection_No internet service',
 'DeviceProtection_Yes',
 'TechSupport_No internet service',
 'TechSupport_Yes',
 'StreamingTV_No internet service',
 'StreamingTV_Yes',
 'StreamingMovies_No internet service',
 'StreamingMovies_Yes',
 'Contract_One year',
 'Contract_Two year',
 'PaperlessBilling_Yes',
 'PaymentMethod_Credit card (automatic)',
 'PaymentMethod_Electronic check',
 'PaymentMethod_Mailed check']

In [19]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   tenure                                 7032 non-null   int64
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   gender_Male                            7032 non-null   int64
 5   Partner_Yes                            7032 non-null   int64
 6   Dependents_Yes                         7032 non-null   int64
 7   PhoneService_Yes                       7032 non-null   int64
 8   MultipleLines_No phone service         7032 non-null   int64
 9   MultipleLines_Yes                      7032 non-null   int64
 10  InternetService_Fiber optic            7032 non-null   int64
 11  InternetService_No                     7032 non-null   int64
 12  OnlineSecurity_No internet service     7032 non-null   int64
 13  OnlineSecurity_Yes                     7032 non-null   int64
 14  OnlineBackup_No internet service       7032 non-null   int64
 15  OnlineBackup_Yes                       7032 non-null   int64
 16  DeviceProtection_No internet service   7032 non-null   int64
 17  DeviceProtection_Yes                   7032 non-null   int64
 18  TechSupport_No internet service        7032 non-null   int64
 19  TechSupport_Yes                        7032 non-null   int64
 20  StreamingTV_No internet service        7032 non-null   int64
 21  StreamingTV_Yes                        7032 non-null   int64
 22  StreamingMovies_No internet service    7032 non-null   int64
 23  StreamingMovies_Yes                    7032 non-null   int64
 24  Contract_One year                      7032 non-null   int64
 25  Contract_Two year                      7032 non-null   int64
 26  PaperlessBilling_Yes                   7032 non-null   int64
 27  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 28  PaymentMethod_Electronic check         7032 non-null   int64
 29  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(28)
memory usage: 1.6 MB

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [21]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print()

print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (5625, 30)
Testing Features  : (1407, 30)

Training Labels   : (5625,)
Testing Labels    : (1407,)

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_columns = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Fit ONLY on training data
X_train_scaled[numerical_columns] = scaler.fit_transform(
    X_train[numerical_columns]
)

# Transform test data using the SAME scaler
X_test_scaled[numerical_columns] = scaler.transform(
    X_test[numerical_columns]
)

In [23]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [24]:
train_data = X_train_scaled.copy()
train_data["Churn"] = y_train

train_data.to_csv(
    "../data/processed/train_scaled.csv",
    index=False
)

In [25]:
test_data = X_test_scaled.copy()
test_data["Churn"] = y_test

test_data.to_csv(
    "../data/processed/test_scaled.csv",
    index=False
)

In [26]:
print("Processed datasets saved successfully!")

Processed datasets saved successfully!

In [27]:
print(train_data.shape)
print(test_data.shape)

(5625, 31)
(1407, 31)

In [28]:
train_data.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
1408,0,1.321816,0.981556,1.659900,1,1,1,1,0,1,...,0,0,0,0,1,0,1,0,0,0
6992,0,-0.267410,-0.971546,-0.562252,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
3349,0,1.444064,0.837066,1.756104,0,1,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
4486,0,-1.204646,0.641092,-0.908326,1,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
3535,0,0.669826,-0.808787,-0.101561,0,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0